Document: thrash-protect
Title: Debian thrash-protect Manual
Author: <insert document author here>
Abstract: This manual describes what thrash-protect is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/thrash-protect/thrash-protect.sgml.gz

Format: postscript
Files: /usr/share/doc/thrash-protect/thrash-protect.ps.gz

Format: text
Files: /usr/share/doc/thrash-protect/thrash-protect.text.gz

Format: HTML
Index: /usr/share/doc/thrash-protect/html/index.html
Files: /usr/share/doc/thrash-protect/html/*.html
